name: Build Main

on:
  push:
    branches:
      - main
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every Monday at 23:26:00 UTC (Monday at 15:26:00 PST)
    # We offset from the hour and half hour to go easy on the servers :)
    - cron: '26 23 * * 1'

jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Python Dependencies
      run: |
        cd python/
        pip install .[test]
    - name: Lint and Format Python
      run: |
        cd python/
        flake8 cdp_example_backend --count --verbose --show-source --statistics
        black --check cdp_example_backend
  
  build-web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Web App Dependencies
      run: |
        cd web/
        npm i
    - name: Lint and Format Web App
      run: |
        cd web/
        npm run lint
    - name: Build Web App
      run: |
        cd web/
        npm run build
