name: Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Infrastructure Deploy
      uses: pulumi/actions@v1
      with:
        command: up -p 5
      env:
        GOOGLE_CREDENTIALS: {% raw %}${{ secrets.GOOGLE_CREDENTIALS }}{% endraw %}
        PULUMI_ACCESS_TOKEN: {% raw %}${{ secrets.PULUMI_ACCESS_TOKEN }}{% endraw %}
        PULUMI_ROOT: infra
