name: Event Processing

on:
  push:
    branches:
      - main
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every day at 0,6,12,18:26:00 UTC
    # We offset from the hour and half hour to go easy on the servers :)
    - cron: '26 0,6,12,18 * * *'

jobs:
  process-events:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Python Dependencies
      run: |
        cd python/
        pip install -r requirements.txt
    - name: Gather and Process New Events
      run: |
        echo "To be added soon..."
