name: CDP Instance Configuration
description: Configure and deploy a new CDP instance.
title: "[Instance]: "
labels:
  - "new instance"
assignees:
  - JacksonMaxfield
body:
  - type: markdown
    attributes:
      value:
        Before beginning on the new instance configuration process, you may want to find out if your municipality uses Legistar for it's legislation and meeting management process. If so, this instance configuration process can be almost entirely automated. If not, you will need to write a custom event scraper. See our documentation on the process [here](https://github.com/CouncilDataProject/cdp-scrapers).


        Additionally, please refer to our documentation on the [cost of maintaining a CDP instance](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment#cost) and affirm that you are able to pay the estimated monthly cost of a new CDP instance.


        Fill out the following information to start the process for deploying a new CDP instance.


        _**Note**, this instance will live under the "CouncilDataProject" GitHub organization and will be hosted under the "councildataproject.org" domain._
  - type: input
    id: municipality_name
    attributes:
      label: Municipality Name
      description: The name of the municipality (town, city, county, etc.) that this CDP Instance will store data for.
      placeholder: ex. "Seattle", "King County"
    validations:
      required: true
  - type: input
    id: municipality_slug
    attributes:
      label: (Optional) Municipality Slug
      description: The name of the municipality cleaned for use in infrastructure and certain parts of repository naming. Default - municipality name lowercased and spaces replaced with '-'.
      placeholder: ex. "seattle", "king-county"
  - type: input
    id: maintainer_github_name
    attributes:
      label: Maintainer GitHub Name
      description: Who will act as the primary maintainer of the new CDP Instance.
      placeholder: ex. "JacksonMaxfield"
    validations:
      required: true
  - type: input
    id: firestore_region
    attributes:
      label: (Optional) Firestore Region
      description: The desired region to host the firestore instance. ([Firestore docs](https://firebase.google.com/docs/firestore/locations)) Default - 'us-central1'.
      placeholder: ex. "us-west1", "us-central1"
  - type: input
    id: legistar_client_id
    attributes:
      label: (Optional) Legistar Client Id
      description: If planning on using Legistar, the municipalities Legistar Client Id as described in above documentation.
      placeholder: ex. "seattle"
  - type: input
    id: timezone
    attributes:
      label: (Optional) Municipality Timezone
      description: If planning on using Legistar, the timezone of your municipality. See [the TZ database name column](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) to find the appropriate timezone string.
      placeholder: ex. "US/Pacific"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/CouncilDataProject/councildataproject.github.io/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
