name: Event Gather

on:
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: '{{ cookiecutter.event_gather_cron }}'
  workflow_dispatch:
    inputs:
      from:
        description: "Optional ISO formatted string for datetime to begin event gather from."
        required: false
        default: ""  # Will get converted to N (default 2) days prior
      to:
        description: "Optional ISO formatted string for datetime to end event gather at."
        required: false
        default: ""  # Will get converted to now

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  deploy-runner-on-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup CML
        uses: iterative/setup-cml@v1
      - name: Create Runner
        env:
          REPO_TOKEN: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
          GOOGLE_APPLICATION_CREDENTIALS_DATA: {% raw %}${{ secrets.GOOGLE_CREDENTIALS }}{% endraw %}
        run: |
          cml runner \
            --single \
            --labels=gcp-cdp-runner \
            --cloud=gcp \
            --cloud-region=us-central1-f \
            --cloud-type=n1-standard-4 \
            --cloud-gpu=nvidia-tesla-t4 \
            --cloud-hdd-size=30 \
            --idle-timeout=600

  process-events:
    needs: [deploy-runner-on-gcp]
    runs-on: [self-hosted, gcp-cdp-runner]
    container:
      image: ghcr.io/iterative/cml:0-dvc2-base1-gpu
      options: --gpus all

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Check GPU Drivers
      run: |
        nvidia-smi

    - name: Install Packages
      run: |
        sudo apt update
        sudo apt-get install -y --no-install-recommends \
          libsndfile1 \
          ffmpeg

    - name: Install Python Dependencies
      run: |
        cd python/
        pip install --upgrade pip
        pip install .

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: {{ cookiecutter.infrastructure_slug }}
        service_account_key: {% raw %}${{ secrets.GOOGLE_CREDENTIALS }}{% endraw %}
        export_default_credentials: true

    - name: Dump Credentials to JSON
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "google-creds.json"
        json: {% raw %}${{ secrets.GOOGLE_CREDENTIALS }}{% endraw %}
        dir: "python/"

    - name: Gather and Process New Events - CRON
      if: {% raw %}${{ github.event_name == 'schedule' }}{% endraw %}
      run: |
        cd python/
        run_cdp_event_gather event-gather-config.json
    
    - name: Gather and Process Requested Events - Manual
      if: {% raw %}${{ github.event_name == 'workflow_dispatch' }}{% endraw %}
      run: |
        cd python/
        {% raw %}run_cdp_event_gather event-gather-config.json \
          --from ${{ github.event.inputs.from }} \
          --to ${{ github.event.inputs.to }}{% endraw %}
