name: Process Special Event

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      event-details-json-string:
        description: "Event details (see EventIngestionModel in cdp-backend) in JSON string form. The string must be free of any newline or tab characters."
        required: true


jobs:
  deploy-runner-on-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup CML
        uses: iterative/setup-cml@v1
      - name: Create Runner
        env:
          REPO_TOKEN: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
          GOOGLE_APPLICATION_CREDENTIALS_DATA: {% raw %}${{ secrets.GOOGLE_CREDENTIALS }}{% endraw %}
        run: |
          cml runner \
            --single \
            --labels=gcp-cdp-runner \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=n1-standard-4 \
            --cloud-gpu=nvidia-tesla-t4 \
            --cloud-hdd-size=30 \
            --idle-timeout=600

  process-events:
    needs: [deploy-runner-gcp-gpu]
    runs-on: [self-hosted, gcp-cdp-runner]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: Install Packages
      run: |
        sudo apt update
        sudo apt-get install -y --no-install-recommends \
          libsndfile1 \
          ffmpeg

    - name: Install Python Dependencies
      run: |
        cd python/
        pip install .

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: {{ cookiecutter.infrastructure_slug }}
        service_account_key: {% raw %}${{ secrets.GOOGLE_CREDENTIALS }}{% endraw %}
        export_default_credentials: true

    - name: Dump Credentials to JSON
      run: |
        echo "$GOOGLE_CREDS" > python/google-creds.json
      env:
        GOOGLE_CREDS: {% raw %}${{ secrets.GOOGLE_CREDENTIALS }}{% endraw %}

    - name: Dump Event Details to JSON
      run: |
        echo {% raw %}${{ github.event.inputs.event-details-json-string }}{% endraw %} > python/event-details.json

    - name: Process special events into event gather pipeline
      if: {% raw %}${{ github.event_name == 'workflow_dispatch' }}{% endraw %}
      run: |
        cd python/
        {% raw %}process_special_event \
          --event_details_file event-details.json \
          --event_gather_config_file event-gather-config.json{% endraw %}
