name: Instance Deployment Bot

on:
  issue_comment:
    types:
      - created

jobs:
  deploy-new-instance:
    runs-on: ubuntu-latest
    if: |
      ${{ github.event.comment.body == '/cdp-deploy' }}

    steps:
      #########################################################################
      # Workflow Setup

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Bot Scripts Dependencies
        run: |
          pip install -r .github/workflows/scripts/requirements.txt
          pip install cookiecutter

      - name: log github context
        run: |
          echo ${{ toJSON(github) }}

      # Run Validation Bot to get Configuration Options
      - name: Dump Issue Body to File
        run: |
          echo "${{ github.event.issue.body }}" > issue-body.md
      - name: Validate Form and Generate Configuration Files
        run: |
          python .github/workflows/scripts/validate-form.py issue-body.md

      #########################################################################
      # Run fast checks

      - name: Read generation-options JSON
        id: genops
        run: |
          content="$(cat generation-options.json)"
          echo "::set-output name=content::$content"

      - name: Error Early - Message
        uses: peter-evans/create-or-update-comment@v1
        if: |
          ${{ fromJSON(steps.genops.outputs.content).scraper_path == null }} ||
          ${{ fromJSON(steps.genops.outputs.content).maintainer_name == null }} ||
          ${{ fromJSON(steps.genops.outputs.content).repository_path == null }}
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## Deployment Status

            :warning: :warning: :warning:

            Not all configuration options are present or some options have errors.

            #### Configuration Options

            ```json
            ${{ steps.genops.outputs.content }}
            ```

            **Stopping Deployment Procedure**
      
      - name: Error Early - Exit
        if: |
          ${{ fromJSON(steps.genops.outputs.content).scraper_path == null }} ||
          ${{ fromJSON(steps.genops.outputs.content).maintainer_name == null }} ||
          ${{ fromJSON(steps.genops.outputs.content).repository_path == null }}
        run: |
          exit 1
    
      #########################################################################
      # Proceed with deployment

      # - name: Read generation-options JSON
      #   id: genops