name: Instance Deployment Bot

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  deploy-new-instance:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: log github context
        run: |
          echo ${{ github }}
