name: Instance Configuration Bot

on:
  issues:
    types:
      - opened

jobs:
  initial-form-check:
    if: ${{ contains(github.event.issue.labels.*.name, 'new instance') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Post Hello
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello! Thank you for initiating the process to configure a new CDP instance.

            I am a bot that will check out the information provided in your form.

            _--initial-form-check--_         
            _This comment was written by a bot!_

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Dump issue body to file
        run: |
          echo "${{ github.event.issue.body }}" > issue-body.md

      - name: Get form value - maintainer
        id: get-maintainer
        run: |
          cat issue-body.md

      # - name: Check for existing repo
      #   uses: actions/checkout@v2
      #     repository: councildataproject/{{}}
