name: Instance Configuration Bot

on:
  issues:
    types:
      - opened

jobs:
  initial-form-check:
    if: ${{ contains(github.event.issue.labels.*.name, 'new instance') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9


      - name: Post Hello
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello! Thank you for initiating the process to configure a new CDP instance.

            I am a bot that will check out the information provided in your form.

            _--initial-form-check--_         
            _This comment was written by a bot!_

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Dump Issue Body to File
        run: |
          echo "${{ github.event.issue.body }}" > issue-body.md

      - name: Get Form Values
        run: |
          target_maintainer=$(python .github/workflows/scripts/get-form-value.py issue-body.md "### Maintainer GitHub Name")

          echo "::set-output name=target_maintainer::$target_maintainer"

          target_repository=$(python .github/workflows/scripts/get-form-value.py issue-body.md "### Repository Name")

          echo "::set-output name=target_repository::$target_repository"

          legistar_client_id=$(python .github/workflows/scripts/get-form-value.py issue-body.md "### Legistar Client Id")

          echo "::set-output name=legistar_client_id::$legistar_client_id"

          legistar_client_timezone=$(python .github/workflows/scripts/get-form-value.py issue-body.md "### Municipality Timezone")

          echo "::set-output name=legistar_client_timezone::$legistar_client_timezone"
          
      - name: Print Form Values
        run: |
          echo ${{ steps.get-maintainer.outputs.target_maintainer }}
          echo ${{ steps.get-maintainer.outputs.target_repository }}
          echo ${{ steps.get-maintainer.outputs.legistar_client_id }}
          echo ${{ steps.get-maintainer.outputs.legistar_client_timezone }}

      - name: Check for existing repo
        uses: actions/checkout@v2
          repository: councildataproject/{{}}
