name: Test Repo Construction

on:
  pull_request:
    branches:
      - main

jobs:
  test-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup languages
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # Run cookiecutter
    - name: Install Cookiecutter
      run: |
        pip install cookiecutter
    - name: Generate Repo
      run: |
        cookiecutter . --no-input
        rm -Rf example/.github/workflows/

    # Check Python
    - name: Install Python Dependencies
      run: |
        cd example/python/
        pip install .[test]
    - name: Lint and Format Python
      run: |
        cd example/python/
        flake8 cdp_example_backend --count --verbose --show-source --statistics
        black --check cdp_example_backend

    # Check Web
    - name: Install Web App Dependencies
      run: |
        cd example/web/
        npm i
    - name: Build Web App
      run: |
        cd example/web/
        npm run build
