name: Test Repo Construction

on:
  pull_request:
    branches:
      - main

jobs:
  test-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup languages
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # Run cookiecutter
    - name: Install Dependencies
      run: |
        pip install cookiecutter
    - name: Generate Repo
      run: |
        cookiecutter . --no-input
        rm -Rf example/.github/workflows/

    # Check Infra
    - name: Run Generated Repo Infrastructure Preview
      uses: docker://pulumi/actions
      with:
        args: preview
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.CDP_EXAMPLE_GOOGLE_CREDENTIALS }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: pr
        PULUMI_ROOT: example/infra

    # Check Python
    - name: Install Generated Repo Python Dependencies
      run: |
        cd example/python/
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint and Format Generated Repo Python
      run: |
        cd example/python/
        flake8 scraper.py --count --verbose --show-source --statistics
        black --check scraper.py

    # Check Web
    - name: Install Generated Repo Web App Dependencies
      run: |
        cd example/web/
        npm i
    - name: Lint and Format Generated Repo Web App
      run: |
        cd example/web/
        npm run lint
    - name: Build Generated Repo Web App
      run: |
        cd example/web/
        npm run build
